title: Coursepack
description: A course pack is a compilation of course materials put into one easy-to-access place for students.
url: http://localhost:4000

collections:
  units:
    output: true
    permalink: /:path/
    layout: unit

defaults:
  - scope:
      type: "units"
    values:
      layout: "unit"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README-*.md
  - README.md
  - coursepack.gemspec
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - yarn.lock
  - /docs
  - /screenshots
